#include "sysfs.h"

#include "../drivers/block_ata.h"
#include "../drivers/rtl8139.h"
#include "../fs/fat.h"
#include "../fs/ramfs.h"
#include "../lib/string.h"
#include "../net/arp.h"
#include "../net/icmp.h"
#include "../net/ip.h"
#include "../net/socket.h"
#include "../net/tcp.h"
#include "../net/udp.h"
#include "../micro/idt.h"
#include "../micro/ipc.h"
#include "../micro/kmalloc.h"
#include "../micro/pmm.h"
#include "../micro/reaper.h"
#include "../micro/scheduler.h"
#include "../micro/timer.h"
#include "../micro/vmm.h"
#include "../micro/service.h"
#include "../micro/task.h"
#include "vfs.h"

/*
 * Each file under /sys is generated by a callback that fills a caller
 * buffer. stat and read both invoke the generator (stat to compute size,
 * read to copy bytes). Keep generators side-effect free.
 */

#define SYSFS_GEN_BUF_SIZE 1024

typedef void (*sysfs_gen_fn)(char *out, size_t out_size);

static void gen_version(char *out, size_t out_size) {
    os_strlcpy(out, "osnos 0.0.1 microkernel-style\n", out_size);
}

static const char *task_state_str(task_state_t s) {
    switch (s) {
        case TASK_READY:   return "READY";
        case TASK_RUNNING: return "RUNNING";
        case TASK_BLOCKED: return "BLOCKED";
        case TASK_STOPPED: return "STOPPED";
        case TASK_ZOMBIE:  return "ZOMBIE";
        case TASK_DEAD:    return "DEAD";
        case TASK_UNUSED:  return "UNUSED";
    }
    return "?";
}

static void gen_tasks(char *out, size_t out_size) {
    out[0] = 0;
    os_strlcat(out, "pid name      state    dispatches\n", out_size);

    for (size_t i = 0; i < MAX_TASKS; i++) {
        const task_t *t = task_slot(i);
        if (!t) continue;

        char num[24];
        os_format_u64(t->pid, num, sizeof(num));
        os_strlcat(out, num, out_size);
        os_strlcat(out, "   ", out_size);

        os_strlcat(out, t->name[0] ? t->name : "?", out_size);
        os_strlcat(out, "  ", out_size);

        os_strlcat(out, task_state_str(t->state), out_size);
        os_strlcat(out, "  ", out_size);

        os_format_u64(t->dispatches, num, sizeof(num));
        os_strlcat(out, num, out_size);
        os_strlcat(out, "\n", out_size);
    }
}

static void append_kv(char *out, size_t out_size,
                       const char *key,
                       uint64_t used, uint64_t total) {
    char num[16];
    os_strlcat(out, key, out_size);
    os_format_u64(used, num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "/", out_size);
    os_format_u64(total, num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\n", out_size);
}

static void gen_meminfo(char *out, size_t out_size) {
    out[0] = 0;

    size_t task_used = 0;
    for (size_t i = 0; i < MAX_TASKS; i++) {
        if (task_slot(i)) task_used++;
    }

    size_t mount_used = 0;
    for (size_t i = 0; i < VFS_MAX_MOUNTS; i++) {
        if (vfs_mount_slot(i)) mount_used++;
    }

    append_kv(out, out_size, "tasks:  ",  task_used,         MAX_TASKS);
    append_kv(out, out_size, "ipc:    ",  ipc_pending(),     IPC_QUEUE_SIZE);
    append_kv(out, out_size, "ramfs:  ",  ramfs_used_count(), RAMFS_MAX_FILES);
    append_kv(out, out_size, "mounts: ",  mount_used,        VFS_MAX_MOUNTS);

    size_t total_kb = (pmm_total_pages() * PAGE_SIZE) / 1024;
    size_t free_kb  = (pmm_free_pages()  * PAGE_SIZE) / 1024;
    size_t used_kb  = total_kb - free_kb;

    char num[24];
    os_strlcat(out, "mem total kB: ", out_size);
    os_format_u64(total_kb, num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nmem used  kB: ", out_size);
    os_format_u64(used_kb, num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nmem free  kB: ", out_size);
    os_format_u64(free_kb, num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\n", out_size);

    os_strlcat(out, "pml4 entries: ", out_size);
    os_format_u64(vmm_pml4_used(vmm_kernel_pml4()), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "/512\n", out_size);

    os_strlcat(out, "kheap total B: ", out_size);
    os_format_u64(kheap_total_bytes(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nkheap used  B: ", out_size);
    os_format_u64(kheap_used_bytes(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nkheap peak  B: ", out_size);
    os_format_u64(kheap_peak_bytes(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nkheap grow / oom: ", out_size);
    os_format_u64(kheap_grow_events(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, " / ", out_size);
    os_format_u64(kheap_grow_oom(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nslab used   B: ", out_size);
    os_format_u64(kheap_slab_used_bytes(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nslab pages   : ", out_size);
    os_format_u64(kheap_slab_pages(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, " (grow ", out_size);
    os_format_u64(kheap_slab_grow_events(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, " / oom ", out_size);
    os_format_u64(kheap_slab_grow_oom(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, ")\nslab buckets : ", out_size);
    for (int i = 0; i < kheap_slab_bucket_count(); i++) {
        if (i > 0) os_strlcat(out, " ", out_size);
        os_format_u64(kheap_slab_bucket_size(i), num, sizeof(num));
        os_strlcat(out, num, out_size);
        os_strlcat(out, ":", out_size);
        os_format_u64(kheap_slab_slots_used(i), num, sizeof(num));
        os_strlcat(out, num, out_size);
        os_strlcat(out, "/", out_size);
        os_format_u64(kheap_slab_slots_total(i), num, sizeof(num));
        os_strlcat(out, num, out_size);
    }
    os_strlcat(out, "\nexceptions  : ", out_size);
    os_format_u64(idt_exception_count(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nreaped tasks: ", out_size);
    os_format_u64(reaper_total_reaped(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nreaper leaks: ", out_size);
    os_format_u64(reaper_leaks(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\n", out_size);
}

static void gen_mounts(char *out, size_t out_size) {
    out[0] = 0;
    for (size_t i = 0; i < VFS_MAX_MOUNTS; i++) {
        const vfs_mount_t *m = vfs_mount_slot(i);
        if (!m) continue;
        os_strlcat(out, m->mountpoint, out_size);
        os_strlcat(out, "\n", out_size);
    }
}

static void gen_uptime(char *out, size_t out_size) {
    out[0] = 0;
    char num[24];

    uint64_t ms  = timer_ms();
    uint64_t sec = ms / 1000;
    uint64_t rem = ms % 1000;

    os_strlcat(out, "seconds:    ", out_size);
    os_format_u64(sec, num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, ".", out_size);
    /* zero-pad ms remainder to 3 digits */
    if (rem < 100) os_strlcat(out, "0", out_size);
    if (rem < 10)  os_strlcat(out, "0", out_size);
    os_format_u64(rem, num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nms:         ", out_size);
    os_format_u64(ms, num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\ntimer ticks:", out_size);
    os_format_u64(timer_ticks(), num, sizeof(num));
    os_strlcat(out, " ", out_size);
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nsched ticks:", out_size);
    os_format_u64(scheduler_get_ticks(), num, sizeof(num));
    os_strlcat(out, " ", out_size);
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\n", out_size);
}

static void gen_timer(char *out, size_t out_size) {
    out[0] = 0;
    char num[24];

    os_strlcat(out, "hz:    ", out_size);
    os_format_u64(TIMER_HZ, num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nticks: ", out_size);
    os_format_u64(timer_ticks(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nms:    ", out_size);
    os_format_u64(timer_ms(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nirqs:  ", out_size);
    os_format_u64(timer_irqs(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\npreempts: ", out_size);
    os_format_u64(timer_preempts(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nwakeups fired: ", out_size);
    os_format_u64(task_wakeups_fired(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\n\nBLOCKED tasks (with wakeup_at_ms set):\n", out_size);
    for (size_t i = 0; i < MAX_TASKS; i++) {
        const task_t *t = task_slot(i);
        if (!t) continue;
        if (t->state != TASK_BLOCKED) continue;
        if (t->wakeup_at_ms == 0)     continue;
        os_strlcat(out, "  pid=", out_size);
        os_format_u64(t->pid, num, sizeof(num));
        os_strlcat(out, num, out_size);
        os_strlcat(out, " wakeup_at_ms=", out_size);
        os_format_u64(t->wakeup_at_ms, num, sizeof(num));
        os_strlcat(out, num, out_size);
        os_strlcat(out, " saved_valid=", out_size);
        os_format_u64((uint64_t)t->saved_valid, num, sizeof(num));
        os_strlcat(out, num, out_size);
        os_strlcat(out, "\n", out_size);
    }
}

static const char *service_name_of(uint64_t id) {
    switch (id) {
        case SERVER_KEYBOARD: return "keyboard";
        case SERVER_SHELL:    return "shell";
        case SERVER_CONSOLE:  return "console";
        case SERVER_FS:       return "fs";
    }
    return "?";
}

static void gen_services(char *out, size_t out_size) {
    out[0] = 0;
    os_strlcat(out, "id  name      pid\n", out_size);

    for (uint64_t id = 1; id <= SERVER_FS; id++) {
        uint64_t pid = service_get_pid(id);
        if (pid == 0) continue;

        char num[16];
        os_format_u64(id, num, sizeof(num));
        os_strlcat(out, num, out_size);
        os_strlcat(out, "   ", out_size);

        os_strlcat(out, service_name_of(id), out_size);
        os_strlcat(out, "  ", out_size);

        os_format_u64(pid, num, sizeof(num));
        os_strlcat(out, num, out_size);
        os_strlcat(out, "\n", out_size);
    }
}

static inline void cpuid(uint32_t leaf,
                         uint32_t *a, uint32_t *b,
                         uint32_t *c, uint32_t *d) {
    __asm__ volatile ("cpuid"
                      : "=a"(*a), "=b"(*b), "=c"(*c), "=d"(*d)
                      : "a"(leaf), "c"(0));
}

static void gen_cpuinfo(char *out, size_t out_size) {
    out[0] = 0;

    uint32_t a, b, c, d;
    cpuid(0, &a, &b, &c, &d);

    char vendor[13];
    os_memcpy(&vendor[0], &b, 4);
    os_memcpy(&vendor[4], &d, 4);
    os_memcpy(&vendor[8], &c, 4);
    vendor[12] = 0;

    os_strlcat(out, "vendor_id : ", out_size);
    os_strlcat(out, vendor, out_size);
    os_strlcat(out, "\n", out_size);

    cpuid(0x80000000, &a, &b, &c, &d);
    if (a >= 0x80000004) {
        char brand[49];
        for (int i = 0; i < 3; i++) {
            cpuid(0x80000002 + (uint32_t)i, &a, &b, &c, &d);
            os_memcpy(&brand[i*16 + 0],  &a, 4);
            os_memcpy(&brand[i*16 + 4],  &b, 4);
            os_memcpy(&brand[i*16 + 8],  &c, 4);
            os_memcpy(&brand[i*16 + 12], &d, 4);
        }
        brand[48] = 0;

        const char *p = brand;
        while (*p == ' ') p++;

        os_strlcat(out, "model name: ", out_size);
        os_strlcat(out, p, out_size);
        os_strlcat(out, "\n", out_size);
    }

    os_strlcat(out, "cores     : 1 (no SMP yet)\n", out_size);
}

static void gen_disks(char *out, size_t out_size) {
    out[0] = 0;

    if (!block_ata_present()) {
        os_strlcat(out, "no ATA disk detected\n", out_size);
        return;
    }

    char num[24];
    os_strlcat(out, "ata0 model:   ", out_size);
    os_strlcat(out, block_ata_model(), out_size);
    os_strlcat(out, "\nata0 sectors: ", out_size);
    os_format_u64(block_ata_sector_count(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nata0 bytes:   ", out_size);
    os_format_u64(block_ata_sector_count() * 512, num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\n", out_size);
}

static void gen_fat_fsck(char *out, size_t out_size) {
    fat_fsck_report(out, out_size);
}

static char hex_nib(uint8_t n) {
    n &= 0xF;
    return (char)(n < 10 ? '0' + n : 'a' + (n - 10));
}

static void gen_arp(char *out, size_t out_size) {
    if (!rtl8139_present()) {
        os_strlcpy(out, "no NIC\n", out_size);
        return;
    }
    arp_dump(out, out_size);
}

static void gen_net(char *out, size_t out_size) {
    out[0] = 0;

    if (!rtl8139_present()) {
        os_strlcat(out, "no NIC detected\n", out_size);
        return;
    }

    /* MAC: cc:cc:cc:cc:cc:cc */
    char macbuf[20];
    const uint8_t *m = rtl8139_mac();
    for (int i = 0; i < 6; i++) {
        macbuf[i * 3 + 0] = hex_nib((uint8_t)(m[i] >> 4));
        macbuf[i * 3 + 1] = hex_nib(m[i]);
        macbuf[i * 3 + 2] = (i < 5) ? ':' : 0;
    }

    char num[24];
    os_strlcat(out, "driver:     rtl8139\n", out_size);
    os_strlcat(out, "mac:        ", out_size);
    os_strlcat(out, macbuf, out_size);
    os_strlcat(out, "\nio_base:    0x", out_size);
    uint16_t io = rtl8139_io_base();
    char hex4[5];
    hex4[0] = hex_nib((uint8_t)(io >> 12));
    hex4[1] = hex_nib((uint8_t)(io >> 8));
    hex4[2] = hex_nib((uint8_t)(io >> 4));
    hex4[3] = hex_nib((uint8_t)io);
    hex4[4] = 0;
    os_strlcat(out, hex4, out_size);
    os_strlcat(out, "\nirq_line:   ", out_size);
    os_format_u64(rtl8139_irq_line(), num, sizeof(num));
    os_strlcat(out, num, out_size);

    os_strlcat(out, "\nirqs:       ", out_size);
    os_format_u64(rtl8139_irqs(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nrx_packets: ", out_size);
    os_format_u64(rtl8139_rx_packets(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\ntx_packets: ", out_size);
    os_format_u64(rtl8139_tx_packets(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nrx_bytes:   ", out_size);
    os_format_u64(rtl8139_rx_bytes(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\ntx_bytes:   ", out_size);
    os_format_u64(rtl8139_tx_bytes(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nerrors:     ", out_size);
    os_format_u64(rtl8139_errors(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\n\nip rx/tx/drop: ", out_size);
    os_format_u64(ip_rx_packets(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, " / ", out_size);
    os_format_u64(ip_tx_packets(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, " / ", out_size);
    os_format_u64(ip_rx_drops(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nicmp rx/tx:    ", out_size);
    os_format_u64(icmp_rx_packets(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, " / ", out_size);
    os_format_u64(icmp_tx_packets(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\nudp rx/tx/drop: ", out_size);
    os_format_u64(udp_rx_packets(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, " / ", out_size);
    os_format_u64(udp_tx_packets(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, " / ", out_size);
    os_format_u64(udp_rx_drops(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\ntcp rx/tx/drop: ", out_size);
    os_format_u64(tcp_rx_packets(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, " / ", out_size);
    os_format_u64(tcp_tx_packets(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, " / ", out_size);
    os_format_u64(tcp_rx_drops(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\ntcp retx/drops: ", out_size);
    os_format_u64(sock_tcp_retx_total(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, " / ", out_size);
    os_format_u64(sock_tcp_retx_drops(), num, sizeof(num));
    os_strlcat(out, num, out_size);
    os_strlcat(out, "\n", out_size);
}

static void gen_build(char *out, size_t out_size) {
    out[0] = 0;
    os_strlcat(out, "compiled: " __DATE__ " " __TIME__ "\n", out_size);
#ifdef __clang_version__
    os_strlcat(out, "compiler: clang " __clang_version__ "\n", out_size);
#endif
}

typedef struct {
    const char  *name;
    sysfs_gen_fn gen;
} sysfs_entry_t;

static const sysfs_entry_t entries[] = {
    { "version",  gen_version  },
    { "build",    gen_build    },
    { "uptime",   gen_uptime   },
    { "cpuinfo",  gen_cpuinfo  },
    { "tasks",    gen_tasks    },
    { "services", gen_services },
    { "mounts",   gen_mounts   },
    { "meminfo",  gen_meminfo  },
    { "timer",    gen_timer    },
    { "disks",    gen_disks    },
    { "fat_fsck", gen_fat_fsck },
    { "net",      gen_net      },
    { "arp",      gen_arp      }
};

#define SYSFS_ENTRY_COUNT (sizeof(entries) / sizeof(entries[0]))

/*
 * Paths under our mount look like "/sys" (the root) or "/sys/<name>".
 * Return the name portion or NULL when the path isn't ours.
 */
static const char *entry_name(const char *path) {
    if (!os_strstarts(path, "/sys")) return 0;
    if (path[4] == 0) return "";       /* the root */
    if (path[4] != '/') return 0;      /* "/sysfoo" -> not ours */
    return path + 5;
}

static const sysfs_entry_t *lookup_entry(const char *name) {
    for (size_t i = 0; i < SYSFS_ENTRY_COUNT; i++) {
        if (os_streq(entries[i].name, name)) return &entries[i];
    }
    return 0;
}

static osnos_status_t sysfs_stat(
    void *priv, const char *path, vfs_stat_t *out
) {
    (void)priv;

    const char *name = entry_name(path);
    if (!name) return OSNOS_ENOENT;

    if (name[0] == 0) {
        out->type  = VFS_NODE_DIR;
        out->size  = 0;
        out->inode = 0;
        out->mode  = 0555;  /* r-x r-x r-x */
        return OSNOS_OK;
    }

    for (size_t i = 0; i < SYSFS_ENTRY_COUNT; i++) {
        if (!os_streq(entries[i].name, name)) continue;

        char tmp[SYSFS_GEN_BUF_SIZE];
        entries[i].gen(tmp, sizeof(tmp));
        out->type  = VFS_NODE_REG;
        out->size  = os_strlen(tmp);
        out->inode = i + 1;        /* 0 reserved for the root */
        out->mode  = 0444;         /* r-- r-- r-- */
        return OSNOS_OK;
    }

    return OSNOS_ENOENT;
}

static osnos_status_t sysfs_readdir(
    void *priv, const char *path, size_t cursor,
    vfs_dirent_t *out, size_t *next_cursor
) {
    (void)priv;

    const char *name = entry_name(path);
    if (!name || name[0] != 0) return OSNOS_ENOENT;

    if (cursor >= SYSFS_ENTRY_COUNT) return OSNOS_ENOENT;

    os_strlcpy(out->name, entries[cursor].name, OSNOS_NAME_MAX);
    out->type = VFS_NODE_REG;
    *next_cursor = cursor + 1;
    return OSNOS_OK;
}

static osnos_status_t sysfs_read(
    void *priv, const char *path,
    char *buf, size_t buf_size, size_t *out_size
) {
    (void)priv;

    const char *name = entry_name(path);
    if (!name) return OSNOS_ENOENT;
    if (name[0] == 0) return OSNOS_EISDIR;

    const sysfs_entry_t *e = lookup_entry(name);
    if (!e) return OSNOS_ENOENT;

    char tmp[SYSFS_GEN_BUF_SIZE];
    e->gen(tmp, sizeof(tmp));

    size_t len = os_strlen(tmp);
    size_t n = (len > buf_size) ? buf_size : len;
    for (size_t i = 0; i < n; i++) buf[i] = tmp[i];
    *out_size = n;
    return OSNOS_OK;
}

static osnos_status_t sysfs_rofs(void *priv, const char *path) {
    (void)priv; (void)path;
    return OSNOS_EROFS;
}

static osnos_status_t sysfs_write(
    void *priv, const char *path, const char *buf, size_t buf_size
) {
    (void)priv; (void)path; (void)buf; (void)buf_size;
    return OSNOS_EROFS;
}

static osnos_status_t sysfs_rename(
    void *priv, const char *src, const char *dst
) {
    (void)priv; (void)src; (void)dst;
    return OSNOS_EROFS;
}

const vfs_ops_t sysfs_vfs_ops = {
    .stat    = sysfs_stat,
    .readdir = sysfs_readdir,
    .read    = sysfs_read,
    .write   = sysfs_write,
    .append  = sysfs_write,
    .mkdir   = sysfs_rofs,
    .rmdir   = sysfs_rofs,
    .unlink  = sysfs_rofs,
    .rename  = sysfs_rename
};
